name: Deploy Agentic Trader

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure target directory exists
        shell: powershell
        run: |
          if (-not (Test-Path "C:\agentic-trader")) {
            New-Item -ItemType Directory -Force -Path "C:\agentic-trader" | Out-Null
          }

      - name: Sync repo to C:\agentic-trader
        shell: powershell
        run: |
          $source = "$env:GITHUB_WORKSPACE"
          $dest   = "C:\agentic-trader"

          robocopy $source $dest *.* /MIR /XD .git .github\workflows /XF .env
          $rc = $LASTEXITCODE
          Write-Host "Robocopy exit code: $rc"

          # Treat 0–3 as success
          if ($rc -le 3) { exit 0 } else { exit $rc }

      - name: Rebuild .env from GitHub Secret
        shell: powershell
        run: |
          $envFile = "C:\agentic-trader\.env"
          Set-Content -Path $envFile -Value "${{ secrets.ENV_FILE_CONTENT }}"
          Write-Host ".env file created at $envFile"

      - name: Install dependencies
        shell: powershell
        run: |
          cd C:\agentic-trader
          python -m venv .venv
          .\.venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
