name: Deploy Agentic Trader

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create application directory
        run: |
          if (!(Test-Path "C:\agentic-trader")) {
            New-Item -ItemType Directory -Path "C:\agentic-trader" | Out-Null
          }

      - name: Deploy code to VPS
        run: |
          robocopy $env:GITHUB_WORKSPACE C:\agentic-trader /MIR /XF .env

      - name: Recreate .env from secret
        run: |
          $envContent = @"
          ${{ secrets.ENV_FILE_CONTENT }}
          "@
          Set-Content -Path "C:\agentic-trader\.env" -Value $envContent -Encoding UTF8

      - name: Install dependencies
        run: |
          cd C:\agentic-trader
          if (!(Test-Path ".venv")) {
            python -m venv .venv
          }
          .\.venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
